name: Gitleaks Secret Scanning - Upload Report

on:
  workflow_run:
    workflows: ["Gitleaks Secret Scanning - Generate Report"]
    types:
      - completed

jobs:
  upload_report:
    name: Upload Gitleaks Report
    runs-on: ubuntu-latest
    steps:
      - name: Download report from previous job
        uses: actions/download-artifact@v4
        with:
          name: gitleaks-report.json

      - name: Upload JSON Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-json
          path: gitleaks-report.json
