name: Gitleaks Secret Scanning

on:
  push:          # Runs on every push
  pull_request:  # Runs on PRs

jobs:
  scan:
    name: Run Gitleaks and Upload Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Gitleaks with JSON Report
      - name: Run Gitleaks (JSON Report)
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          report-format: json
          report-path: gitleaks-report.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload JSON Report as Artifact
      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-json
          path: gitleaks-report.json

      # Run Gitleaks with CSV Report
      - name: Run Gitleaks (CSV Report)
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          report-format: csv
          report-path: gitleaks-report.csv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload CSV Report as Artifact
      - name: Upload CSV Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-csv
          path: gitleaks-report.csv

      # Run Gitleaks with SARIF Report for GitHub Security Integration
      - name: Run Gitleaks (SARIF Report)
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          report-format: sarif
          report-path: gitleaks-report.sarif
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload SARIF Report to GitHub Security Scanning
      - name: Upload SARIF Report for Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
